### ISSUE TITLE
Unknown method invocation `printExceptions` on NfcoreSchema type

### ISSUE THREAD

**Issue by mahesh-panchal** [mahesh-panchal/test_nfcore_workflow_chain#1]
Using these steps in the root dir of https://github.com/mahesh-panchal/test_nfcore_workflow_chain/commit/e3b51fdfc5c0dd5f2285fef901b6577a84de77a5
```
ln -s subworkflows/fetchngs/lib lib
nf-core schema build
```
leads to:
```console
$ make test 
bash run_workflow.sh
Picked up JAVA_TOOL_OPTIONS:  -Xmx3435m
N E X T F L O W  ~  version 21.10.6
Launching `main.nf` [suspicious_feynman] - revision: 31a6c995e0

ERROR: Validation of pipeline parameters failed!


Unknown method invocation `printExceptions` on NfcoreSchema type

 -- Check script 'subworkflows/fetchngs/main.nf' at line: 20 or see '.nextflow.log' file for more details
make: *** [Makefile:10: test] Error 1
```

**Comment by mahesh-panchal** [comment]
Log stack trace:
```
Feb-22 19:00:44.731 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingMethodException: No signature of method: static NfcoreSchema.printExceptions() is applicable for argument types: (org.json.JSONObject, org.json.JSONObject, ch.qos.logback.classic.Logger) values: [{"pointerToViolation":"#","causingExceptions":[{"schemaLocation":"#/definitions/input_output_options/properties/input","pointerToViolation":"#/input","causingExceptions":[],"keyword":"pattern","message":"string [data/ids.txt] does not match pattern ^\\S+\\.csv$"}],"keyword":"allOf","message":"#: only 4 subschema matches out of 5"}, ...]
	at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1584)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1570)
	at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.callStatic(StaticMetaClassSite.java:62)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:249)
	at NfcoreSchema.printExceptions(NfcoreSchema.groovy:365)
	at NfcoreSchema.printExceptions(NfcoreSchema.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:149)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:100)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:258)
	at NfcoreSchema.validateParameters(NfcoreSchema.groovy:162)
	at NfcoreSchema.validateParameters(NfcoreSchema.groovy)
	at NfcoreSchema$validateParameters.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
	at WorkflowMain.initialise(WorkflowMain.groovy:58)
	at WorkflowMain$initialise.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
	at Script_e16ebd84.runScript(Script_e16ebd84:20)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:169)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:207)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:201)
	at nextflow.script.IncludeDef.memoizedMethodPriv$loadModule0PathMapSession(IncludeDef.groovy:142)
	at nextflow.script.IncludeDef.access$0(IncludeDef.groovy)
	at nextflow.script.IncludeDef$__clinit__closure1.doCall(IncludeDef.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at nextflow.script.IncludeDef.loadModule0(IncludeDef.groovy)
	at nextflow.script.IncludeDef.load0(IncludeDef.groovy:114)
	at nextflow.script.IncludeDef$load0$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at Script_25dd2027.runScript(Script_25dd2027:5)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:169)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:308)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)

```

**Comment by mahesh-panchal** [comment]
Make change L365 at NfcoreSchema.groovy:
```
printExceptions(ex, params_json, log)
```
to 
```
printExceptions(ex, params_json, log, enums)
```
gives more reasonable output.
```
$ make test
bash run_workflow.sh
Picked up JAVA_TOOL_OPTIONS:  -Xmx3435m
N E X T F L O W  ~  version 21.10.6
Launching `main.nf` [disturbed_mcnulty] - revision: 31a6c995e0

ERROR: Validation of pipeline parameters failed!


* --input: string [data/ids.txt] does not match pattern ^\S+\.csv$ (data/ids.txt)




WARN: Found unexpected parameters:
* --rnaseq_outdir: rnaseq_data
* --fetchngs_outdir: fetchngs_data
* --skip_fastq_download: false
* --force_sratools_download: false
* --synapse_config: null
* --sample_mapping_fields: experiment_accession,run_accession,sample_accession,experiment_alias,run_alias,sample_alias,experiment_title,sample_title,sample_description,description
* --ena_metadata_fields: null
* --nf_core_pipeline: null
* --input_type: sra
- Ignore this warning: params.schema_ignore_params = "rnaseq_outdir,fetchngs_outdir,skip_fastq_download,force_sratools_download,synapse_config,sample_mapping_fields,ena_metadata_fields,nf_core_pipeline,input_type" 

make: *** [Makefile:10: test] Error 1

```

**Comment by mahesh-panchal** [comment]
Fixed the `nextflow_schema.json` to accept txt instead of csv.
New errror:
```
$ make test
bash run_workflow.sh
Picked up JAVA_TOOL_OPTIONS:  -Xmx3435m
N E X T F L O W  ~  version 21.10.6
Launching `main.nf` [nasty_noyce] - revision: 31a6c995e0
JSONObject["properties"] not found.

 -- Check script 'subworkflows/fetchngs/main.nf' at line: 20 or see '.nextflow.log' file for more details
make: *** [Makefile:10: test] Error 1
```
The log traces it to line 392 of NfcoreSchema.groovy
```
if (definition[key].get("properties").keySet().contains(ignore_param)){
```
The code above implies a `definitions` block in the JSON schema. ✔️ 
For each map in definitions, get the "properties" value of that map. 
Present:
- "input_output_options", 
- "institutional_config_options", 
- "max_job_request_options", 
- "generic_options"

Absent:
- "reference_genome_options"

Rebuilding the Nextflow JSON schema without "reference_genome_options" fixes it.
